CREATE TABLE PUBLIC.PRICES (
	ID IDENTITY,
	BRAND_ID SMALLINT,
	START_DATE TIMESTAMP,
	END_DATE TIMESTAMP,
	PRICE_LIST SMALLINT,
	PRODUCT_ID INTEGER,
	PRIORITY TINYINT DEFAULT 0,
	PRICE DECIMAL(8,2) DEFAULT 0,
	CURR VARCHAR(3) DEFAULT 'EUR',
	CONSTRAINT PK_PRICES PRIMARY KEY (ID)
);
CREATE INDEX PRICES_BRAND_ID_IDX ON PUBLIC.PRICES (BRAND_ID,START_DATE,END_DATE,PRODUCT_ID);
